# Generated by Django 4.2.19 on 2025-02-25 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ammunition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ammunition_type", models.CharField(max_length=64)),
                ("lot_number", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Armorer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_exp_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Armory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=64)),
                ("total_magazines", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("service_branch", models.CharField(max_length=32)),
                ("total_service_members", models.IntegerField()),
                ("commanding_officer", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Firearm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firearm_type", models.CharField(max_length=64)),
                ("serial_number", models.CharField(max_length=64)),
                ("maintenance_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=64)),
                ("state", models.CharField(max_length=32)),
                ("zip_code", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qual_type", models.CharField(max_length=64)),
                ("completion_date", models.DateField()),
                ("expiration_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ServiceMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=32)),
                ("last", models.CharField(max_length=32)),
                ("rate", models.CharField(max_length=8)),
                ("rank", models.CharField(max_length=8)),
                ("end_of_service_date", models.DateField()),
                (
                    "command_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="armory.command"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Watch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watch_type", models.CharField(max_length=32)),
                ("is_qualified", models.BooleanField()),
                ("check_out", models.DateField()),
                ("check_in", models.DateField()),
                ("ammunition_count", models.IntegerField()),
                ("ammunition_id", models.ManyToManyField(to="armory.ammunition")),
                (
                    "armory_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="armory.armorer"
                    ),
                ),
                ("firearm_id", models.ManyToManyField(to="armory.firearm")),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="armory.servicemember",
                    ),
                ),
                ("qualification_id", models.ManyToManyField(to="armory.qualification")),
            ],
        ),
        migrations.CreateModel(
            name="Magazine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_m9", models.IntegerField()),
                ("total_m4a1", models.IntegerField()),
                ("total_9mm", models.IntegerField()),
                ("total_556", models.IntegerField()),
                ("total_762", models.IntegerField()),
                (
                    "armory_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="armory.armory"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="firearm",
            name="magazine_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.magazine"
            ),
        ),
        migrations.AddField(
            model_name="command",
            name="location_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.location"
            ),
        ),
        migrations.AddField(
            model_name="armory",
            name="command_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.command"
            ),
        ),
        migrations.AddField(
            model_name="armorer",
            name="armory_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.armory"
            ),
        ),
        migrations.AddField(
            model_name="armorer",
            name="member_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.servicemember"
            ),
        ),
        migrations.AddField(
            model_name="ammunition",
            name="firearm_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.firearm"
            ),
        ),
        migrations.AddField(
            model_name="ammunition",
            name="magazine_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.magazine"
            ),
        ),
    ]
