# Generated by Django 5.1.6 on 2025-02-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('service_branch', models.CharField(max_length=32)),
                ('total_service_members', models.IntegerField()),
                ('commanding_officer', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=32)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qual_type', models.CharField(max_length=64)),
                ('completion_date', models.DateField()),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Armory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=64)),
                ('total_magazines', models.IntegerField()),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.command')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.location'),
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_m9', models.IntegerField()),
                ('total_m4a1', models.IntegerField()),
                ('total_9mm', models.IntegerField()),
                ('total_556', models.IntegerField()),
                ('total_762', models.IntegerField()),
                ('armory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.armory')),
            ],
        ),
        migrations.CreateModel(
            name='Firearm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firearm_type', models.CharField(max_length=64)),
                ('serial_number', models.CharField(max_length=64)),
                ('maintenance_date', models.DateField()),
                ('magazine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.magazine')),
            ],
        ),
        migrations.CreateModel(
            name='Ammunition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammunition_type', models.CharField(max_length=64)),
                ('lot_number', models.CharField(max_length=64)),
                ('firearm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.firearm')),
                ('magazine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.magazine')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=32)),
                ('last', models.CharField(max_length=32)),
                ('rate', models.CharField(max_length=8)),
                ('rank', models.CharField(max_length=8)),
                ('end_of_service_date', models.DateField()),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.command')),
            ],
        ),
        migrations.CreateModel(
            name='Armorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_exp_date', models.DateField()),
                ('armory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.armory')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.servicemember')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_type', models.CharField(max_length=32)),
                ('is_qualified', models.BooleanField()),
                ('check_out', models.DateField()),
                ('check_in', models.DateField()),
                ('ammunition_count', models.IntegerField()),
                ('ammunition_id', models.ManyToManyField(to='armory.ammunition')),
                ('armory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.armorer')),
                ('firearm_id', models.ManyToManyField(to='armory.firearm')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.servicemember')),
                ('qualification_id', models.ManyToManyField(to='armory.qualification')),
            ],
        ),
    ]
