# Generated by Django 4.2.19 on 2025-03-18 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("armory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicemember",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicemember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
