# Generated by Django 4.2.19 on 2025-03-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0002_servicemember_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="servicemember_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="armory.servicemember",
            ),
        ),
    ]
