# Generated by Django 4.2.19 on 2025-03-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0003_qualification_servicemember_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="check_in",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="watch",
            name="check_out",
            field=models.DateTimeField(),
        ),
    ]
