# Generated by Django 5.1.6 on 2025-03-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0004_alter_watch_check_in_alter_watch_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
