# Generated by Django 4.2.19 on 2025-04-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0005_firearm_available"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name="watch",
            name="watch_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armory.watchtype"
            ),
        ),
    ]
