# Generated by Django 5.1.6 on 2025-03-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0005_alter_watch_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='firearm',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
