# Generated by Django 4.2.19 on 2025-04-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0006_watchtype_alter_watch_watch_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watch",
            name="ammunition_id",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="qualification_id",
        ),
    ]
