# Generated by Django 5.1.6 on 2025-03-25 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0006_firearm_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='armory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armory.armorer'),
        ),
    ]
