# Generated by Django 4.2.19 on 2025-04-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0007_remove_watch_ammunition_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="check_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
