# Generated by Django 5.1.6 on 2025-03-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0007_alter_watch_armory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ammunition',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magazine',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
