# Generated by Django 4.2.19 on 2025-04-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory", "0008_alter_watch_check_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="count_556",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="watch",
            name="count_762",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="watch",
            name="count_9mm",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="watch",
            name="ammunition_count",
            field=models.IntegerField(default=0),
        ),
    ]
