# Generated by Django 5.1.6 on 2025-03-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0008_ammunition_quantity_magazine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='returned_556',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magazine',
            name='returned_762',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magazine',
            name='returned_9mm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magazine',
            name='returned_M4A1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magazine',
            name='returned_M9',
            field=models.IntegerField(default=0),
        ),
    ]
