# Generated by Django 5.1.6 on 2025-04-03 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0009_magazine_returned_556_magazine_returned_762_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='returned_556',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='returned_762',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='returned_9mm',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='returned_M4A1',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='returned_M9',
        ),
        migrations.CreateModel(
            name='IssuedAmmunition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.IntegerField()),
                ('ammunition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.ammunition')),
                ('watch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory.watch')),
            ],
        ),
    ]
