# Generated by Django 5.1.6 on 2025-04-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0010_remove_magazine_returned_556_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuedammunition',
            old_name='ammunition_id',
            new_name='ammunition',
        ),
        migrations.RenameField(
            model_name='issuedammunition',
            old_name='watch_id',
            new_name='watch',
        ),
    ]
